// 042: market-tape контракт re-source из @trdlabs/sdk kernel (единый источник).
export {
  CANONICAL_EVENT_ORDER,
  MARKET_TAPE_EVENT_KINDS,
  compareMarketTapeEvents,
} from '@trdlabs/sdk/research-contract';
export type {
  BarCloseEvent,
  CoverageModel,
  FundingPoint,
  FundingReading,
  FundingSnapshot,
  FundingSnapshotEvent,
  HistoricalMarketTape,
  KindCoverage,
  LiqPoint,
  LiqSnapshotEvent,
  LiquidationSnapshot,
  MarketDataCoverageState,
  MarketDataGap,
  MarketDataKind,
  MarketTape,
  MarketTapeDataset,
  MarketTapeEvent,
  MarketTapeEventKind,
  MinuteColumn,
  OiPoint,
  OiSnapshotEvent,
  OpenInterestSnapshot,
  PointInTimeMarketApi,
  RawMarketTapeSource,
  RawMarketTapeSymbolColumns,
  TakerPoint,
  TakerReading,
  TakerSnapshot,
  TakerSnapshotEvent,
  TapeBuildResult,
} from '@trdlabs/sdk/research-contract';
